### PR TITLE
fix and improve sops task

### PR DESCRIPTION
**Pull request by brunnels**
- fixed sops:encrypt task
- added sops:decrypt task

#1539

### CODE REVIEW

**Comment by onedr0p** [comment]
As of sops 3.9.0 we can now use the filestatus arg, so this can be improved in other ways

**Comment by onedr0p** [comment]
E.g.

```
sops filestatus cluster-secrets.secret.sops.yaml | jq --exit-status '.encrypted'
```

**Comment by brunnels** [comment]
I'll update the PR with the new features

**Comment by onedr0p** [comment]
Closing this PR, feel free to try again when you have time.

**Pull request closed without merging**
