### PR TITLE
feat(talos): add Talos and kubernetes version for talconfig

### PR DESCRIPTION
**Pull request by remkolems**
* Added Talos version
* Added kubernetes version
* Corrected minor grammar typo

Followed https://factory.talos.dev/ for talosImageURL construction. Testing of other versions than latest release of Talos is now possible.

### CODE REVIEW

**Comment by onedr0p** [comment]
This breaks renovating the talhelper config file for those versions.

**Comment by remkolems** [comment]
Are you sure btw? Because talconfig generates just fine:

image

**Comment by onedr0p** [comment]
If you're saying that the version has to be stapled onto the talosImageURL I'm not sure the best way to handle this. Maybe talhelper might need some work done to append the version for us automatically.

**Comment by remkolems** [comment]
> If you're saying that the version has to be stapled onto the talosImageURL I'm not sure the best way to handle this. Maybe talhelper might need some work done to append the version for us automatically.

That was indeed my main trigger for this pull request. Tried to solve this as cleanly as possible.

image

versus (https://factory.talos.dev)

image

**Comment by remkolems** [comment]
Don't know yet if a default Talos version can be generated within this cluster template setup.

Besides that end-users could select a different version on https://factory.talos.dev

**Comment by remkolems** [comment]
Fortunately the schematicID does (not seem) to change between the different Talos versions. So... only the stapled version is maybe an issue.

**Comment by onedr0p** [comment]
I've reached out to the talhelper dev to request a feature that might help us here. Let's see what the feedback is from him before we take this route.

**Comment by onedr0p** [comment]
In the meantime you could do this with the talenv.yaml file instead. You could move the Renovate comments, and talos / kubernetes version to this file and reference them as vars in the talhelper config

See this example for the built in variable substitution in talhelper https://github.com/buroa/k8s-gitops/tree/master/talos

This might be the supported way forward from the developer but we'll see.

**Comment by remkolems** [comment]
I'll close this pull request. Just tested with Talhelper and the Talos version is stapled onto the talosImageURL. So it was a non-issue after all. My apologies.

image

If others - me included - want to have another Talos/Kubernetes version, they just can edit the talconfig file. Least resistance and the least maintenance burden on this cluster template.

**Pull request closed without merging**
